/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package trixware.erp.prodezydesktop.planning;

import javax.swing.BoxLayout;

/**
 *
 * @author Rajesh
 */
public class AllocHorizontalPanel extends javax.swing.JPanel {

    /**
     * Creates new form AllocHorizontalPanel
     */
    public AllocHorizontalPanel () {
        
    }
    
    public AllocHorizontalPanel ( boolean[] enableValueField ) {
        initComponents ();

        int x = enableValueField.length ;
        
        if( x>8 ){
            setLayout ( new BoxLayout ( this , BoxLayout.X_AXIS ) );    
        }else{
            setLayout ( new BoxLayout ( this , BoxLayout.X_AXIS ) );    
            setSize(  x*100, 75      );
        }
        
      // int width, height ;
        
      //  width = getSize ().width ;
     //   height = getSize ().height ;
        
        for ( int i = 0 ; i < x ; i ++ ) {
            TempPanel1 tp1 = new TempPanel1 ();
            add( tp1 ) ;
            tp1.enableTextField ( enableValueField[i] );
        }
        

        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings( "unchecked" )
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(100, 70));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
