/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package trixware.erp.prodezydesktop.planning;

import javax.swing.BoxLayout;
import javax.swing.JPanel;
import javax.swing.JTextField;

/**
 *
 * @author Rajesh
 */
public class TempPanel1 extends javax.swing.JPanel {

    /**
     * Creates new form TempPanel1
     */
    public TempPanel1 () {
        initComponents ();        
    }

        
    public void adjustTextField(){
        int width, height ;
        width =  jTextField1.getParent ().getWidth ()  ;
        height = jTextField1.getParent ().getHeight ()   ;
        jTextField1.setBounds(  ( width - 70)/2 , 15,   80, 40  ) ;      
        System.out.println ( ""+( width - 70)/2 +"   "+  width +"             "+ height+"    "   );
        revalidate ();
        repaint ();
    }
    
    public void enableTextField(   boolean value  ){
        jTextField1.setEnabled ( value );
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings( "unchecked" )
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(100, 75));
        setLayout(null);

        jTextField1.setFont(new java.awt.Font("Leelawadee UI", 0, 16)); // NOI18N
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField1.setText("0");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        add(jTextField1);
        jTextField1.setBounds(10, 15, 80, 40);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
